version: "3.8"

services:

  php-apache:
    depends_on:
      - mysql-db
      - redis-session
    container_name: xxxxx-php-apache
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
      target: php_dev
    volumes:
      - ./.docker/php-apache/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php-apache/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php-apache/conf/apache/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./src:/srv/src
      - .:/srv
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=
      - DB_USERNAME=xxxxx_admin
      - DB_PASSWORD=xxxxx_admin
      - CACHE_PREFIX=
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_CONNECTION=sessions
      - REDIS_SESSION_HOST=redis-session
      - REDIS_SESSION_PASSWORD=null
      - REDIS_SESSION_PORT=6379
      - REDIS_SESSION_DATABASE=0
      - LOG_DIR=/srv/log
      - LOG_LEVEL=info
    ports:
      - 8000:80

  mysql-db:
    container_name: xxxxx-mysql-db
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - ./.docker/mysql/var/lib/mysql:/var/lib/mysql
      - ./.docker/mysql/logs:/var/log/mysql
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
      - TZ='Asia/Tokyo'
    ports:
      - 13306:3306

  redis-session:
    container_name: xxxxx-redis-session
    image: "redis:6.2.6-alpine"
    ports:
      - "6379:6379"
    volumes:
      - ".docker/redis:/data"

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    container_name: xxxxx-phpmyadmin
    ports:
      - 8008:80
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

  phpredisadmin:
    depends_on:
      - redis-session
    image: erikdubbelboer/phpredisadmin
    container_name: xxxxx-phpredisadmin
    ports:
      - 8009:80
    environment:
      - REDIS_1_HOST=redis-session
      - REDIS_1_NAME=xxxxx-session
